services:
  jupyter:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    working_dir: /app
    stdin_open: true
    tty: true
  dev:
    build: .
    volumes:
      - .:/app
    command: bash
    working_dir: /app
    stdin_open: true
    tty: true